networks:
  default:
    name:
      prnotifybot-network

services:
  prnotifybot:
    container_name: prnotifybot
    build: .
    tty: true
    stdin_open: true
    ports:
      - "80:5000"
    environment:
      TG_API_ID: ${TG_API_ID}
      TG_API_HASH: ${TG_API_HASH}
      TG_CHAT_NAME: ${TG_CHAT_NAME}
      WH_SECRET: ${WH_SECRET}
    volumes:
      - tgdata:/app/tgdata

volumes:
  tgdata:
